x-base: &base
  image: djangobox/django-docker-box:${PYTHON_VERSION}
  build:
    context: ${DJANGO_PATH}
    dockerfile: ${PWD}/Containerfile
    args:
    - PYTHON_VERSION=${PYTHON_VERSION}
    cache_from:
    - djangobox/django-docker-box:${PYTHON_VERSION}
  volumes:
  - ${DJANGO_PATH}:/tests/django/
  - ./settings.py:/tests/django/tests/settings.py
  entrypoint: bash -c "wait-for-it.sh -s -t 20 $${WAIT_FOR} -- python runtests.py $$@" --

x-postgres-base: &postgres-base
  environment:
  - POSTGRES_USER=django
  - POSTGRES_PASSWORD=django
  - POSTGRES_DB=django
  # Set a few options to speed up postgresql tests.
  command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
  tmpfs:
  - /var/lib/postgresql

services:
  sqlite:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.db.backends.sqlite3
    entrypoint: python runtests.py
    depends_on:
    - memcached
    - memcached2

  sqlite-gis:
    <<: *base
    entrypoint: python runtests.py
    environment:
    - DATABASE_ENGINE=django.contrib.gis.db.backends.spatialite

  postgres:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.db.backends.postgresql
    - DATABASE_HOST=postgres-db
    - WAIT_FOR=postgres-db:5432
    depends_on:
    - postgres-db
    - memcached
    - memcached2
  postgres-db:
    <<: *postgres-base
    image: postgres:${POSTGRES_VERSION}-alpine

  postgres-gis:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.contrib.gis.db.backends.postgis
    - DATABASE_HOST=postgres-gis-db
    - WAIT_FOR=postgres-gis-db:5432
    depends_on:
    - postgres-gis-db
  postgres-gis-db:
    <<: *postgres-base
    image: postgis/postgis:${POSTGRES_VERSION}-${POSTGIS_VERSION}

  mysql:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.db.backends.mysql
    - DATABASE_HOST=mysql-db
    - WAIT_FOR=mysql-db:3306
    depends_on:
    - mysql-db
    - memcached
    - memcached2
  mysql-db: &mysql_base
    image: mysql:${MYSQL_VERSION}
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    tmpfs:
    - /var/lib/mysql
    environment:
    - MYSQL_USER=django
    - MYSQL_PASSWORD=django
    - MYSQL_DATABASE=django
    - MYSQL_ALLOW_EMPTY_PASSWORD=1

  mysql-gis:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.contrib.gis.db.backends.mysql
    - DATABASE_HOST=mysql-gis-db
    - WAIT_FOR=mysql-gis-db:3306
    depends_on:
    - mysql-gis-db
  mysql-gis-db:
    <<: *mysql_base
    volumes:
    - /var/lib/mysql

  mariadb:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.db.backends.mysql
    - DATABASE_HOST=mariadb-db
    - WAIT_FOR=mariadb-db:3306
    depends_on:
    - mariadb-db
    - memcached
    - memcached2
  mariadb-db:
    image: mariadb:${MARIADB_VERSION}
    tmpfs:
    - /var/lib/mysql
    environment:
    - MYSQL_USER=django
    - MYSQL_PASSWORD=django
    - MYSQL_DATABASE=django
    - MYSQL_ALLOW_EMPTY_PASSWORD=1

  memcached: &memcached
    image: memcached:alpine

  memcached2:
    <<: *memcached

  docs:
    <<: *base
    entrypoint: ["make", "spelling"]
    working_dir: /tests/django/docs
    user: root

  flake8:
    <<: *base
    entrypoint: flake8

  # Browser tests
  chrome:
    <<: *base
    command: --selenium=chrome --selenium-hub=http://chrome-browser:4444/wd/hub
    environment:
    - DATABASE_ENGINE=django.db.backends.sqlite3
    - WAIT_FOR=chrome-browser:4444
    depends_on:
      - chrome-browser
  chrome-browser:
    image: selenium/standalone-chrome
    volumes:
    - /dev/shm:/dev/shm

  # Firefox tests fail on main
  firefox:
    <<: *base
    command: --selenium=firefox --selenium-hub=http://firefox-browser:4444/wd/hub
    environment:
    - DATABASE_ENGINE=django.db.backends.sqlite3
    - WAIT_FOR=firefox-browser:4444
    depends_on:
    - firefox-browser
  firefox-browser:
    image: selenium/standalone-firefox
    volumes:
    - /dev/shm:/dev/shm
