name: ci

on:
  push:
    branches:
      - 'main'
  workflow-dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.10]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/django-docker-box
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
            context: .
            push: true
            build-args: ${{ matrix.python-version }}
            labels: ${{ steps.meta.outputs.labels }}
            tags: ${{ matrix.python-version }}

